#!/usr/bin/env node

const path = require('pathe');

const cwd = path.resolve(process.cwd());
const pkg = require(path.join(cwd, 'package.json'));
console.log('get package name %s from %s', pkg.name, cwd);
